name: debtlint
description: Identifies repeated or near-duplicate code segments across a codebase.
author: poc-innovation
branding:
  icon: "check-circle"
  color: "green"

inputs:
  files:
    description: "File passed to the program."
    required: false


runs:
  using: composite
  steps:
    - name: Setup nu shell
      uses: hustcer/setup-nu@v3
      with:
        version: 0.114.1
    
    - name: Add .cargo/bin to PATH
      shell: nu {0}
      run: |
        $"($env.HOME)/.cargo/bin" | save --append $env.GITHUB_PATH
    
    - name: Install debtlint
      shell: nu {0}
      run: cargo install debtlint
    
    - name: Install dependencies
      shell: nu {0}
      working-directory: ${{ github.action_path }}
      run: npm install
  
    - name: Run debtlint
      shell: nu {0}
      env:
        GITHUB_TOKEN: ${{ env.GITHUB_TOKEN }}
      run: npx tsx --tsconfig action/tsconfig.json ${{ github.action_path }}/main.ts