name: Check duplication

on:
  push:

jobs:
    debtlint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v6

            - name: Run debtlint
              uses: ./action
              with:
               files: "src"