name: Publish crate

on:
  push:
    tags:
      - 'v[0-9]+\.[0-9]+\.[0-9]+'

jobs:
    publish_package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Install rust
              run: |
                curl https://sh.rustup.rs -sSf -y | sh
                cargo install cargo-set-version

            - name: Update package version
              run:  |
                cargo set-version ${GITHUB_REF_NAME#v}
                cargo update
                git config user.name "github-actions[bot]"
                git config user.email "github-actions[bot]@users.noreply.github.com"
                git add Cargo.toml Cargo.lock
                git commit -m "Update version to ${GITHUB_REF_NAME}."
                git push origin HEAD:refs/heads/${vars.RELEASE_BRANCH}

            - name: Publish package
              run: |
                echo ${{ secrets.CARGO_REGISTRY_TOKEN }} | cargo login
                cargo publish