name: Publish crate

on:
  push:
    tags:
      - 'v*'

env:
    NEW_VERSION: ${{ github.ref_name }}

jobs:
    publish_package:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v6

            - name: Install rust
              run: curl https://sh.rustup.rs -sSf | sh -y

            - name: Update package version
              run: cargo set-version ${ env.NEW_VERSION#v }
            
            - name: Publish package
              run: |
                cargo login ${{ secrets.CARGO_REGISTRY_TOKEN }}
                cargo publish