name: Quality

on:
  pull_request:
    paths: ['**.rs']

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Install rustfmt
        run: rustup component add rustfmt
    
      - name: Check format
        run: cargo fmt --all --check
      
      - name: Run linter
        run: cargo clippy -- -Dwarnings